oauth2:
  user:
    github:
      client-id: Ov23ctHp2vZJoN3WHd25
      client-secret: ac5fe963fa674067ac6ea35a9912322b27b17309
      redirect-uri: https://www.issuetracker.site/login/oauth2/code/github
    google:
      client-id:
      client-secret:
      redirect-uri:
    naver:
      client-id:
      client-secret:
      redirect-uri:
  provider:
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me

spring:
  profiles:
    include: oauth
