name: Deploy to ECR

on:
  push:
    branches: [ deploy ]

concurrency:
  group: issue-tracker-back-end-ecs
  cancel-in-progress: true
  
jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      run: |
        cd ${{ github.workspace }}/BE
        docker build -f src/Dockerfile -t issue-tracker-prod-ecr .
        docker tag issue-tracker-prod-ecr:latest 891377102486.dkr.ecr.ap-northeast-2.amazonaws.com/issue-tracker-prod-ecr:latest
        docker push 891377102486.dkr.ecr.ap-northeast-2.amazonaws.com/issue-tracker-prod-ecr:latest